// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyzayqvlqnunzzjtnnsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5emF5cXZscW51bnp6anRubnNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxOTIwMjAsImV4cCI6MjA0OTc2ODAyMH0.6r0RZbvF7-e6Crki7z6kXgVjpvvhvQVDXRroqXSp9VY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);